import cx_Oracle
import os
import glob
from drop_tables import drop_tables
from delete_migrations import delete_migrations
from makemigrations_and_migrate import makemigrations_and_migrate
from show_tables import show_tables

# ---- CONFIGURATIONS -> CHANGE THIS PART ----
CHECK_DB = False  # If database should be dropped or not
DBNAME = "orcl"
PANDORA_ROOT = os.path.abspath('.')
DBUSER = 'cfdadmin'
DBPASSWORD = 'pandora123$321#'
# DBHOST = '13.234.237.100'
DBHOST = 'cfduat.c0be6oyqiohf.ap-south-1.rds.amazonaws.com'


# postgresql://cfdadmin@cfduat.c0be6oyqiohf.ap-south-1.rds.amazonaws.com/orcl
DBPATH = '{username}/{password}@{host}/{db_name}'.format(
														username=DBUSER, 
														password=DBPASSWORD, host=DBHOST,
                                                        db_name=DBNAME
                                                    )

# DBUSER = 'cfd'
# DBPASSWORD = 'Password123'


# https://cx-oracle.readthedocs.io/en/latest/installation.html
con = cx_Oracle.connect(DBUSER, DBPASSWORD, f"{DBHOST}/{DBNAME}")

print('Connection ', con)

def main():
	import sys

	# http://www.jochenhebbrecht.be/site/2010-05-10/database/drop-all-tables-in-oracle-db-scheme
	DROP_TABLES_QUERY = '''SELECT \'DROP TABLE "\' || TABLE_NAME || \'" CASCADE CONSTRAINTS;\' FROM user_tables'''

	SELECT_QUERY_MASTERDATA = 'SELECT * FROM MASTERDATA_COUNTRY';

	SELECT_QUERY_KYCDETAILS = 'SELECT * FROM INVESTOR_KYCDETAILS'

	SELECT_SCHEMA = 'ALTER SESSION SET CURRENT_SCHEMA = schema1'
	# cursor.execute(query)


	SHOW_TABLES_QUERY = """SELECT
	  table_name, owner
	FROM
	  dba_tables
	WHERE
	  owner='CFDADMIN'
	ORDER BY
	  owner, table_name"""

	mm_commands = [
		"python3 manage.py makemigrations users",
		"python3 manage.py makemigrations tenants",
		'python3 manage.py makemigrations tests',
		"python3 manage.py migrate"
	]

	project_root = '/Users/hygull/Projects/Python3/DjangoTenantOracleSchemas/django-tenant-oracle-schemas/src'



	if len(sys.argv) > 2:
		print(sys.argv)
		investor_id = sys.argv[2]
		operation_type = sys.argv[1]
		print(investor_id)

		INSERT_INVESTOR_QUERY = "INSERT INTO INVESTOR_KYCDETAILS(ID,BANK_NAME,IFSC,CITY,BRANCH,DISTRICT, STATE,PHONE, ADDRESS,OFFICE) \
			VALUES (%d,SBI,SBIN000012,BANGALORE,BELLANDUR,)" % (investor_id)
		execute_query(INSERT_INVESTOR_QUERY)
		return
	elif len(sys.argv) == 2:
		operation_type = sys.argv[1]
	else:
		operation_type = 1

	INVESTORPROFILE_QUERY = """SELECT * FROM INVESTOR_INVESTORPROFILE"""

	if operation_type == '1':
		drop_tables(con, DROP_TABLES_QUERY)
	elif operation_type == '2':
		print('Deleting migrations')
		delete_migrations(pycaches=True)
	elif operation_type == '3':
		print(__file__)
		print(os.path.abspath(__file__))
		this_dir = os.path.dirname(os.path.abspath(__file__))
		makemigrations_and_migrate(project_root, this_dir, mm_commands)
		# return
	elif operation_type == '4':
		show_tables(con, SHOW_TABLES_QUERY)


	con.close()

if __name__ == "__main__":
	main()
	# pass

"""
(venv3.6.7) ➜  tests git:(master) ✗ python3 oracle-connect.py
12.1.0.2.0
CURSOR  <cx_Oracle.Cursor on <cx_Oracle.Connection to cfdadmin@cfduat.c0be6oyqiohf.ap-south-1.rds.amazonaws.com/orcl>>
EXECUTING QUERY ->  SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables
('DROP TABLE "PRODUCTS_SCHEMEINTEREST" CASCADE CONSTRAINTS;',)
('DROP TABLE "PRODUCTS_SCHEMERATING" CASCADE CONSTRAINTS;',)
('DROP TABLE "DJANGO_SESSION" CASCADE CONSTRAINTS;',)
('DROP TABLE "DJANGO_SITE" CASCADE CONSTRAINTS;',)
('DROP TABLE "SOCIALACCOUNT_SOCIALACCOUNT" CASCADE CONSTRAINTS;',)
('DROP TABLE "SOCIALACCOUNT_SOCIALAPP" CASCADE CONSTRAINTS;',)
('DROP TABLE "SOCIALACCOUNT_SOCIALAPP_SITES" CASCADE CONSTRAINTS;',)
('DROP TABLE "SOCIALACCOUNT_SOCIALTOKEN" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_CERTIFICATE" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_CHEQUEPAYMENT" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_NEFTPAYMENT" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_ORDER" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_ORDERACTIVITY" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_ORDERDOCUMENTS" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_ORDERITEM" CASCADE CONSTRAINTS;',)
('DROP TABLE "TRANSACTIONS_PAYMENTGATEWAY" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_INVESTORUSERDISTR8B2E" CASCADE CONSTRAINTS;',)
('DROP TABLE "DJANGO_MIGRATIONS" CASCADE CONSTRAINTS;',)
('DROP TABLE "DJANGO_CONTENT_TYPE" CASCADE CONSTRAINTS;',)
('DROP TABLE "AUTH_PERMISSION" CASCADE CONSTRAINTS;',)
('DROP TABLE "AUTH_GROUP" CASCADE CONSTRAINTS;',)
('DROP TABLE "AUTH_GROUP_PERMISSIONS" CASCADE CONSTRAINTS;',)
('DROP TABLE "USERS_USER" CASCADE CONSTRAINTS;',)
('DROP TABLE "USERS_USER_GROUPS" CASCADE CONSTRAINTS;',)
('DROP TABLE "USERS_USER_USER_PERMISSIONS" CASCADE CONSTRAINTS;',)
('DROP TABLE "USERS_SESSIONUSER" CASCADE CONSTRAINTS;',)
('DROP TABLE "USERS_URLDETAILS" CASCADE CONSTRAINTS;',)
('DROP TABLE "USERS_VENDORCREDENTIALS" CASCADE CONSTRAINTS;',)
('DROP TABLE "ACCOUNT_EMAILADDRESS" CASCADE CONSTRAINTS;',)
('DROP TABLE "ACCOUNT_EMAILCONFIRMATION" CASCADE CONSTRAINTS;',)
('DROP TABLE "DJANGO_ADMIN_LOG" CASCADE CONSTRAINTS;',)
('DROP TABLE "AUTHTOKEN_TOKEN" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_APIKEY" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILBCC" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILCATEGORY" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILFILE" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILFROMEMAIL" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILFROMEMAILCREDENTIAL" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILGROUP" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILGROUPEMAIL" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILLOG" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILLOGEMAIL" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILLOGEXCEPTION" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILLOGTRACK" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILTEMPLATE" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILTEMPLATE_BCC_EMAIL" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_SIGNAL" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_SIGNALDEFERREDDISPATCH" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_SIGNALLOG" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILBASETEMPLATE" CASCADE CONSTRAINTS;',)
('DROP TABLE "DBMAIL_MAILSUBSCRIPTION" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_ASSET" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_ASSETDISTRIBUTORMAP" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_ATTRIBUTE" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_DISTRIBUTOR" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_DISTRIBUTORUSERMAP" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_DISTRIBUTORVENDORMAP" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_VENDOR" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_VENDORMETA" CASCADE CONSTRAINTS;',)
('DROP TABLE "ENTITY_VENDORUSERMAP" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_ACCOUNTTYPE" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_ACTIVENFE" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_APPLICABLEINCOME" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_BANK" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_BANKBILLDESK" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_COUNTRY" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_EXEMPTION" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_GETHOLDINGNATURE" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_GIINEXEMPTION" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_IDTYPE" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_IFSC" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_LOCATION" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_OCCUPATION" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_PANEXEMPTCATEGORY" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_PAYMENTMECHANISM" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_PINCODEMASTER" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_SOURCEWEALTH" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_STATE" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_TAXSTATUS" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_TRANSACTIONTYPE" CASCADE CONSTRAINTS;',)
('DROP TABLE "MASTERDATA_UBO" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_ADDRESS" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_BANKDETAIL" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_DOCUMENTLIST" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_DOCUMENTUPLOAD" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_ENTITYINVESTORMAP" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_INVESTORNOMINEEDETAIL" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_INVESTORPROFILE" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_INVESTORUSERMAP" CASCADE CONSTRAINTS;',)
('DROP TABLE "INVESTOR_KYCDETAILS" CASCADE CONSTRAINTS;',)
('DROP TABLE "PRODUCTS_AGENCY" CASCADE CONSTRAINTS;',)
('DROP TABLE "PRODUCTS_INTERESTFREQUENCY" CASCADE CONSTRAINTS;',)
('DROP TABLE "PRODUCTS_PERIOD" CASCADE CONSTRAINTS;',)
('DROP TABLE "PRODUCTS_SCHEME" CASCADE CONSTRAINTS;',)
('DROP TABLE "TENANTS_TENANT" CASCADE CONSTRAINTS;',)
"""
