# Generated by Django 2.2.2 on 2019-06-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'tenant_name')},
        ),
    ]
